import SwiftUI

struct ReportCardView: View {
    let title: String
    let date: Date
    let resp: TextEvalResp
    let dimensions: [RadarDimension]

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            header

            Divider()

            // 雷达图 + 图例（导出时固定左右布局，更像"报告"）
            HStack(alignment: .top, spacing: 16) {
                RadarChart(dimensions: dimensions)
                    .frame(width: 320, height: 320)

                RadarLegend(dimensions: dimensions)
                    .frame(width: 260)
            }

            Divider()

            // 分数卡
            HStack(spacing: 12) {
                scoreCard("Fluency", resp.fluency)
                scoreCard("Completeness", resp.completeness)
                scoreCard("Relevance", resp.relevance)
            }

            if let suggestions = resp.suggestions, !suggestions.isEmpty {
                Divider()
                VStack(alignment: .leading, spacing: 8) {
                    Text("Suggestions")
                        .font(.headline)
                    ForEach(suggestions.prefix(5), id: \.self) { s in
                        Text("• \(s)")
                            .font(.callout)
                            .foregroundStyle(.secondary)
                    }
                }
            }

            Spacer(minLength: 0)

            Text("Generated by Ai_Say")
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .padding(24)
        .frame(width: 680, height: 920) // iPad 导出固定尺寸，稳定
        .background(Color(.systemBackground))
    }

    private var header: some View {
        HStack {
            VStack(alignment: .leading, spacing: 6) {
                Text(title)
                    .font(.largeTitle).bold()
                Text(date, style: .date)
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
            }
            Spacer()
            Image(systemName: "graduationcap.fill")
                .font(.system(size: 40))
                .foregroundStyle(.secondary)
        }
    }

    private func scoreCard(_ name: String, _ value: Double) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(name)
                .font(.caption)
                .foregroundStyle(.secondary)
            Text(String(format: "%.0f", value))
                .font(.title).bold()
                .monospacedDigit()
        }
        .frame(maxWidth: .infinity, minHeight: 72, alignment: .leading)
        .padding(12)
        .background(Color(.secondarySystemBackground))
        .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
    }
}